# Generated by Django 4.2.4 on 2024-05-26 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('ambulance_number', models.CharField(max_length=17)),
                ('amb_availablity', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_phone', models.CharField(max_length=11)),
                ('customer_type', models.IntegerField(choices=[(1, 'Private'), (2, 'Business')])),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=255)),
                ('drop_of_location', models.CharField(max_length=255)),
                ('pick_up_time', models.DateTimeField(default=datetime.datetime(2024, 5, 26, 21, 2, 22, 436588))),
                ('num_of_floors', models.PositiveIntegerField()),
                ('pick_from_institution', models.BooleanField(default=False)),
                ('drop_at_institution', models.BooleanField(default=False)),
                ('devision_name', models.CharField(blank=True, max_length=100, null=True)),
                ('elvator_in_home', models.BooleanField(default=False)),
                ('need_oxygen', models.BooleanField(default=False)),
                ('need_stretcher', models.BooleanField(default=False)),
                ('need_wheel_chair', models.BooleanField(default=False)),
                ('patient_weight', models.PositiveIntegerField()),
                ('two_stuff_needed', models.BooleanField(default=False)),
                ('number_of_stuff_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('have_preferred_driver', models.BooleanField(default=False)),
                ('return_trip', models.BooleanField(default=False)),
                ('return_trip_pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_of_location', models.CharField(max_length=100)),
                ('pick_up_time', models.DateTimeField(default=datetime.datetime(2024, 5, 26, 21, 2, 22, 437658))),
                ('number_of_stuff_needed', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('charge_number', models.CharField(blank=True, max_length=5, null=True)),
                ('Am_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customer')),
                ('customer_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EqInAmbulance',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_name', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('am_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
            ],
        ),
        migrations.RemoveField(
            model_name='buser',
            name='image',
        ),
        migrations.AddField(
            model_name='buser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AlterField(
            model_name='buser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Manager')]),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=100, unique=True)),
                ('institution_adress', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('in_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.institution')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('eq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.eqinambulance')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customerride')),
            ],
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='dropoff_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_ins', to='BubblanceApp.institution'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='pickup_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_ins', to='BubblanceApp.institution'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='preferred_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.buser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='institution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.institution'),
        ),
        migrations.CreateModel(
            name='AmbulanceCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 5, 26, 21, 2, 22, 435586))),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('ambulance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to='BubblanceApp.buser')),
                ('sec_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to='BubblanceApp.buser')),
            ],
        ),
    ]
