# Generated by Django 4.2.3 on 2023-12-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buser',
            name='image',
        ),
    ]
