# Generated by Django 4.2.3 on 2023-12-09 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0002_remove_buser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('ambulance_number', models.CharField(max_length=17)),
                ('amb_availablity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_phone', models.CharField(max_length=11)),
                ('customer_type', models.IntegerField(choices=[(1, 'Private'), (2, 'Business')])),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_of_location', models.CharField(max_length=100)),
                ('pick_up_time', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 51, 48, 980))),
                ('num_of_floors', models.PositiveIntegerField()),
                ('devision_name', models.CharField(blank=True, max_length=100, null=True)),
                ('elvator_in_home', models.BooleanField(default=False)),
                ('need_oxygen', models.BooleanField(default=False)),
                ('need_stretcher', models.BooleanField(default=False)),
                ('need_wheel_chair', models.BooleanField(default=False)),
                ('patient_weight', models.PositiveIntegerField()),
                ('number_of_stuff_needed', models.PositiveIntegerField()),
                ('return_trip', models.BooleanField(default=False)),
                ('return_trip_pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_of_location', models.CharField(max_length=100)),
                ('pick_up_time', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 51, 48, 980))),
                ('number_of_stuff_needed', models.PositiveIntegerField()),
                ('Am_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customer')),
                ('customer_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('eq_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100, unique=True)),
                ('institution_adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='buser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Manager')]),
        ),
        migrations.CreateModel(
            name='EquipmentInRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('eq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.equipment')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.customerride')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.equipmenttype'),
        ),
        migrations.CreateModel(
            name='Eq_in_Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('Am_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
                ('eq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='preferred_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.buser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='institution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.institution'),
        ),
        migrations.CreateModel(
            name='AmbulanceCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 51, 47, 999976))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ambulance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to='BubblanceApp.buser')),
                ('sec_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to='BubblanceApp.buser')),
            ],
        ),
    ]
