# Generated by Django 4.2.4 on 2024-07-06 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0013_alter_ambulancecrew_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerride',
            name='driver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.buser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerride',
            name='drop_of_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 40, 25, 911000)),
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 40, 25, 908991)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 40, 25, 909999)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 40, 25, 911000)),
        ),
    ]
