# Generated by Django 4.2.4 on 2024-07-06 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0014_customerride_driver_id_customerride_drop_of_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 13, 58, 21, 723651)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Business')], default=2),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 13, 58, 21, 725155)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='drop_of_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 13, 58, 21, 726157)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 13, 58, 21, 726157)),
        ),
    ]
