# Generated by Django 4.2.3 on 2023-12-16 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0017_alter_ambulancecrew_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='ambulancecrew',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='buser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='customerride',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='eq_in_ambulance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='equipmentinride',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1),
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 15, 31, 668464)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 15, 31, 670475)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 15, 31, 670475)),
        ),
    ]
