# Generated by Django 4.2.14 on 2024-07-13 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0021_alter_ambulancecrew_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buser',
            name='current_location',
            field=models.CharField(default='Kakal St 7, Petah Tikva', max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 13, 34, 4, 752319)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 13, 34, 4, 752823)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='drop_of_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 13, 34, 4, 753825)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 13, 34, 4, 753825)),
        ),
    ]
