# Generated by Django 4.2.14 on 2024-07-13 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0022_buser_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 17, 32, 29, 331607)),
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='buser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 17, 32, 29, 332608)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='drop_of_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 17, 32, 29, 332608)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 17, 32, 29, 332608)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='eqinambulance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Ongoing')], default=1),
        ),
    ]
