# Generated by Django 4.2.3 on 2024-01-13 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0023_customerride_charge_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 17, 29, 38, 411974)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='drop_of_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 17, 29, 38, 413983)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 17, 29, 38, 413983)),
        ),
    ]
