# Generated by Django 4.2.3 on 2024-01-13 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0024_alter_ambulancecrew_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqInAmbulance',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_name', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=1)),
                ('am_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.ambulance')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='eq_type_id',
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 18, 35, 11, 109775)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 18, 35, 11, 110787)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 18, 35, 11, 110787)),
        ),
        migrations.DeleteModel(
            name='Eq_in_Ambulance',
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
        migrations.AlterField(
            model_name='equipmentinride',
            name='eq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubblanceApp.eqinambulance'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
