# Generated by Django 4.2.4 on 2024-05-11 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0028_alter_ambulancecrew_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='two_stuff_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 32, 39, 344418)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 32, 39, 344923)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 32, 39, 345928)),
        ),
    ]
