# Generated by Django 4.2.4 on 2024-05-11 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0029_customerrequest_two_stuff_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 33, 28, 560785)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='number_of_stuff_needed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 33, 28, 562289)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 33, 28, 563312)),
        ),
    ]
