# Generated by Django 4.2.14 on 2024-07-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubblanceApp', '0044_alter_ambulancecrew_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecrew',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 20, 17, 8, 77489)),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 20, 17, 8, 80015)),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='drop_of_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='drop_of_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerride',
            name='pick_up_time',
            field=models.DateTimeField(),
        ),
    ]
